blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/community
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: mailto:security@example.com
    about: Please report security vulnerabilities privately.
